### ISSUE TITLE
fatal: unable to access 'https://opendev.org/zuul/zuul-jobs/': Could not resolve proxy: https_proxy

### ISSUE THREAD

**Issue by dzintars** [dzintars/zuul#1]
`execuor` fails when following [zuul-ci.org/docs/zuul/latest/tutorials/quick-start.html#configure-a-base-job](https://zuul-ci.org/docs/zuul/latest/tutorials/quick-start.html#configure-a-base-job)

![image](https://github.com/dzintars/zuul/assets/547420/2abdcc6b-e0a8-4770-853f-4951e6aed824)

**Comment by dzintars** [comment]
From the host i can clone the repository just fine.

**Comment by dzintars** [comment]
```bash
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher: Unexpected issue in _run loop:
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:   Traceback (most recent call last):
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/zuul/driver/git/gitwatcher.py", line 158, in run
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       self.watcher_election.run(self._run)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/zuul/zk/election.py", line 28, in run
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       return super().run(func, *args, **kwargs)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/kazoo/recipe/election.py", line 54, in run
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       func(*args, **kwargs)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/zuul/driver/git/gitwatcher.py", line 149, in _run
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       self._poll()
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/zuul/driver/git/gitwatcher.py", line 127, in _poll
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       refs = self.lsRemote(project)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:              ^^^^^^^^^^^^^^^^^^^^^^
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/zuul/driver/git/gitwatcher.py", line 72, in lsRemote
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       output = client.ls_remote(
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:                ^^^^^^^^^^^^^^^^^
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 741, in <lambda>
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1315, in _call_process
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       return self.execute(call, **exec_kwargs)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     File "/usr/local/lib/python3.11/site-packages/git/cmd.py", line 1109, in execute
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:       raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:   git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     cmdline: git ls-remote --heads --tags https://opendev.org/zuul/zuul-jobs
2023-06-02 20:21:25,983 ERROR zuul.connection.git.watcher:     stderr: 'fatal: unable to access 'https://opendev.org/zuul/zuul-jobs/': Could not resolve proxy: ${https_proxy}'
```

**Comment by dzintars** [comment]
I think, it's related to these stanzas:
```yaml
          env:
            - name: http_proxy
              value: ${http_proxy}
            - name: https_proxy
              value: ${https_proxy}
            - name: no_proxy
              value: ${no_proxy},gerrit
```

**Comment by dzintars** [comment]
I think, it's related to these stanzas:
```yaml
          env:
            - name: http_proxy
              value: ${http_proxy}
            - name: https_proxy
              value: ${https_proxy}
            - name: no_proxy
              value: ${no_proxy},gerrit
```

**Comment by dzintars** [comment]
Fixed those, but there is another issue somewhere.

**Comment by dzintars** [comment]
You don't need to set values or to use configMap to provide proxy values (url's).
